Repository DreamVault-2024/dreamvalut-backend, pull requests merged in 2024-05, with the labels that each got.

#81 BE/#40 `PlaylistService` - `CreatePlaylist()` 메소드 로직 수정
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
Labels: 🏷 Fix

#83 Fix: `JwtVerifyFilter` - whitelist에 `/search` 경로 추가
  src/main/java/com/example/dreamvalutbackend/config/jwt/filter/JwtVerifyFilter.java
Labels: 🏷 Fix

#85 BE/#42 `AuthenticationPriciple`이 필요한 API에 사용자 식별 로직 붙이기 && `getPlaylistWithTracks()`에서 플레이리스트 소유 정보 추가 반환
  src/main/java/com/example/dreamvalutbackend/config/jwt/filter/JwtVerifyFilter.java
  src/main/java/com/example/dreamvalutbackend/domain/genre/controller/GenreController.java
  src/main/java/com/example/dreamvalutbackend/domain/genre/service/GenreService.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/PlaylistController.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/response/PlaylistWithTracksResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
  src/main/java/com/example/dreamvalutbackend/domain/search/controller/SearchController.java
  src/main/java/com/example/dreamvalutbackend/domain/search/service/SearchService.java
  src/main/java/com/example/dreamvalutbackend/domain/tag/controller/TagController.java
  src/main/java/com/example/dreamvalutbackend/domain/tag/service/TagService.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/TrackController.java
  src/main/java/com/example/dreamvalutbackend/domain/track/service/TrackService.java
Labels: 🏷 Fix, 🚀 Feat, 🧹 Refactor

#86 Be/#38 User 곡 , 플레이리스트, 취향 API 구현
  src/main/java/com/example/dreamvalutbackend/config/SecurityConfig.java
  src/main/java/com/example/dreamvalutbackend/config/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/dreamvalutbackend/config/handler/CommonLoginSuccessHandler.java
  src/main/java/com/example/dreamvalutbackend/config/jwt/filter/JwtVerifyFilter.java
  src/main/java/com/example/dreamvalutbackend/config/jwt/utils/JwtUtils.java
  src/main/java/com/example/dreamvalutbackend/config/oauth2/domain/GoogleUserInfo.java
  src/main/java/com/example/dreamvalutbackend/config/oauth2/domain/KakaoUserInfo.java
  src/main/java/com/example/dreamvalutbackend/config/oauth2/domain/NaverUserInfo.java
  src/main/java/com/example/dreamvalutbackend/config/oauth2/domain/OAuth2UserInfo.java
  src/main/java/com/example/dreamvalutbackend/config/oauth2/service/OAuth2UserService.java
  src/main/java/com/example/dreamvalutbackend/domain/genre/domain/Genre.java
  src/main/java/com/example/dreamvalutbackend/domain/like/controller/LikeController.java
  src/main/java/com/example/dreamvalutbackend/domain/like/controller/response/LikeWithTracksOverviewResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/like/repository/LikeRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/like/service/LikeService.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/PlaylistController.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/MyPlaylistRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/PlaylistRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/PlaylistTrackRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/TrackController.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/response/TrackThumbnailImageResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/response/UserCreateTrackResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/track/service/TrackService.java
  src/main/java/com/example/dreamvalutbackend/domain/user/controller/UserController.java
  src/main/java/com/example/dreamvalutbackend/domain/user/controller/request/GenreCreateRequestDto.java
  src/main/java/com/example/dreamvalutbackend/domain/user/controller/request/UserGenreCreateRequestDto.java
  src/main/java/com/example/dreamvalutbackend/domain/user/controller/request/UserPreferenceUpdateRequest.java
  src/main/java/com/example/dreamvalutbackend/domain/user/controller/response/UserGenreResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/user/domain/SocialType.java
  src/main/java/com/example/dreamvalutbackend/domain/user/domain/User.java
  src/main/java/com/example/dreamvalutbackend/domain/user/domain/UserGenre.java
  src/main/java/com/example/dreamvalutbackend/domain/user/repository/UserGenreRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/user/service/UserService.java
  src/main/resources/static/index.html
Labels: 🏷 Fix, 🚀 Feat

#89 Feat: `SwaggerConfig`에 테스트 서버 도메인 추가
  src/main/java/com/example/dreamvalutbackend/config/swagger/SwaggerConfig.java
Labels: 🚀 Feat

#90 Be/#44 JwtVerifyFilter 도메인 허용 whitelist user추가 및 도메인명 수정
  src/main/java/com/example/dreamvalutbackend/config/jwt/filter/JwtVerifyFilter.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/PlaylistController.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/TrackController.java
Labels: 🚀 Feat

#95 BE/#47 Cors, RedirectURL 및 Swagger 설정 관련 URL들 프로퍼티로 치환 && 배포관련 파일 변경
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  prod.Dockerfile
  src/main/java/com/example/dreamvalutbackend/config/SecurityConfig.java
  src/main/java/com/example/dreamvalutbackend/config/handler/CommonLoginSuccessHandler.java
  src/main/java/com/example/dreamvalutbackend/config/swagger/SwaggerConfig.java
Labels: 🏷 Fix, 🚀 Feat

#97 Be/#45 인기차트 api ,팔로우한 플레이리스트 형식 수정 및 구현
  src/main/java/com/example/dreamvalutbackend/config/jwt/filter/JwtVerifyFilter.java
  src/main/java/com/example/dreamvalutbackend/config/swagger/SwaggerConfig.java
  src/main/java/com/example/dreamvalutbackend/domain/like/service/LikeService.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/PlaylistController.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/MyPlaylistRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/PlaylistRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/PlaylistRepositoryCustom.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/repository/PlaylistRepositoryImpl.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/TrackController.java
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/response/TrackRankResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepositoryCustom.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepositoryImpl.java
  src/main/java/com/example/dreamvalutbackend/domain/track/service/TrackService.java
Labels: 🏷 Fix, 🚀 Feat

#101 Be/#49 api 값 수정 및 기존 유저 redirect url 수정
  src/main/java/com/example/dreamvalutbackend/config/SecurityConfig.java
  src/main/java/com/example/dreamvalutbackend/config/handler/CommonLoginSuccessHandler.java
  src/main/java/com/example/dreamvalutbackend/config/jwt/utils/JwtConstants.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/response/PlaylistWithTracksResponseDto.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
  src/main/java/com/example/dreamvalutbackend/domain/user/repository/UserGenreRepository.java
Labels: 🏷 Fix, 🚀 Feat

#105 BE/#50 `deploy.yml` 오타 수정
  .github/workflows/deploy.yml
Labels: 🏷 Fix

#109 BE/#51 곡 등록 시, 새로 생성되는 태그는 해당 곡의 이미지를 이용해서 태그 이미지로 사용하도록 설정
  src/main/java/com/example/dreamvalutbackend/domain/tag/service/TagService.java
Labels: 🏷 Fix

#108 BE/#52 로그인 redirecturl 변경
  src/main/java/com/example/dreamvalutbackend/config/handler/CommonLoginSuccessHandler.java
Labels: 🏷 Fix

#110 Merge: 로그인 리다이렉트 URL 변경 및 태그 생성 시, 이미지 적용 로직 수정 main 브랜치로 머지
  .github/workflows/deploy.yml
  src/main/java/com/example/dreamvalutbackend/config/handler/CommonLoginSuccessHandler.java
  src/main/java/com/example/dreamvalutbackend/domain/tag/service/TagService.java
Labels: 🏷 Fix

#113 BE/#53 track 최신곡 받아오기 오류 수정
  src/main/java/com/example/dreamvalutbackend/domain/track/controller/TrackController.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepository.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepositoryCustom.java
  src/main/java/com/example/dreamvalutbackend/domain/track/repository/StreamingHistoryRepositoryImpl.java
  src/main/java/com/example/dreamvalutbackend/domain/track/service/TrackService.java
Labels: 🏷 Fix

#115 BE/#54 `PlaylistController` - `getPlaylistsWithTracksOverview()`와 `getPlaylistWithTracks()` 정렬 기준 변경
  src/main/java/com/example/dreamvalutbackend/domain/playlist/controller/PlaylistController.java
  src/main/java/com/example/dreamvalutbackend/domain/playlist/service/PlaylistService.java
Labels: 🏷 Fix
